---
devices:
  leaf1:
    ip: 10.240.40.30
    desc: leaf
    credentials: root_account
    active: true
    bundle: MyBundle
  leaf2:
    ip: 10.240.40.31
    desc: leaf
    ssh:
      port: '22'
    credentials: root_account
  spine1:
    ip: 10.240.40.51
    desc: leaf
    ssh:
      port: '22'
    credentials: root_account
    active: true


credentials:
  root_account:
    username: root
    password: root123
  root_account2:
    username: root
    password: admin123


bundle:
  junos-qfx:
    - junos_CLI_L2.sh
    - junos_CLI_CONFIG.sh
  MyBundle:
    - junos_CLI_BGP.sh
    - junos_CLI_L2.sh